apiVersion: v1
kind: Pod
metadata:
  name: demo
  labels:
    app: demo
spec:
  containers:
  - name: demo
    image: docker.io/jsenon/demo-istio:latest
    env:
    - name: MY_VERSION
      value: "v.0.0.1"
    - name: "MY_ANSWER_CODE"
      value: "200"
    imagePullPolicy: Always
    ports:
    - containerPort: 9010