apiVersion: v1
kind: Service
metadata:
  name: demo-svc
  labels:
    app: demo
spec:
  selector:
    app: demo
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 9010
  type: LoadBalancer