apiVersion: v1
kind: Service
metadata:
  name: demo-istio
  labels:
    app: demo-istio
spec:
  selector:
    app: demo-istio
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 9010