kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: demo-vol
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2
